CREATE TABLE IF NOT EXISTS people_images (
    id SERIAL PRIMARY KEY,
    nome TEXT,
    etnia TEXT,
    cor_cabelo TEXT,
    faixa_etaria TEXT,
    caminho_imagem TEXT
);

TRUNCATE TABLE people_images RESTART IDENTITY CASCADE;

INSERT INTO people_images (nome, etnia, cor_cabelo, faixa_etaria, caminho_imagem)
VALUES
('Julia', 'branca', 'grisalho', '60+', '/img/pessoa_001.jpg'),
('Carlos', 'branca', 'grisalho', '60+', '/img/pessoa_002.jpg'),
('Mariana', 'branca', 'castanho', '41-60', '/img/pessoa_003.jpg'),
('Sandra', 'branca', 'loiro', '41-60', '/img/pessoa_004.jpg'),
('Fernanda', 'branca', 'ruivo', '26-40', '/img/pessoa_005.jpg'),
('Lucas', 'branca', 'preto', '26-40', '/img/pessoa_006.jpg'),
('Marcela', 'branca', 'loiro', '0-5', '/img/pessoa_007.jpg'),
('Marina', 'branca', 'preto', '0-5', '/img/pessoa_008.jpg'),
('Julio', 'branca', 'loiro', '5-12', '/img/pessoa_009.jpg'),
('Lucas2', 'branca', 'loiro', '5-12', '/img/pessoa_010.jpg'),
('Marina2', 'branca', 'castanho', '13-17', '/img/pessoa_011.jpg'),
('Rafaela', 'branca', 'loiro', '18-25', '/img/pessoa_012.jpg'),
('Luiz', 'negra', 'grisalho', '60+', '/img/pessoa_013.jpg'),
('Marcelo', 'negra', 'preto', '60+', '/img/pessoa_014.jpg'),
('Tais', 'negra', 'preto', '13-17', '/img/pessoa_015.jpg'),
('Michael', 'negra', 'preto', '13-17', '/img/pessoa_016.jpg'),
('Djalma', 'negra', 'preto', '18-25', '/img/pessoa_017.jpg'),
('Michele', 'negra', 'castanho', '18-25', '/img/pessoa_018.jpg'),
('Francisco', 'negra', 'preto', '26-40', '/img/pessoa_019.jpg'),
('Thais', 'negra', 'preto', '41-60', '/img/pessoa_020.jpg'),
('Robson', 'negra', 'preto', '41-60', '/img/pessoa_021.jpg'),
('Marcos', 'negra', 'preto', '41-60', '/img/pessoa_022.jpg'),
('Samuel', 'negra', 'preto', '5-12', '/img/pessoa_023.jpg'),
('Anderson', 'negra', 'preto', '0-5', '/img/pessoa_024.jpg'),
('Kenji', 'asiatica', 'castanho', '5-12', '/img/pessoa_025.jpg'),
('Yumi', 'asiatica', 'castanho', '5-12', '/img/pessoa_026.jpg'),
('Hana', 'asiatica', 'castanho', '18-25', '/img/pessoa_027.jpg'),
('Takeshi', 'asiatica', 'loiro', '13-17', '/img/pessoa_028.jpg'),
('Mei', 'asiatica', 'preto', '41-60', '/img/pessoa_029.jpg'),
('Kakashi', 'asiatica', 'castanho', '41-60', '/img/pessoa_030.jpg'),
('Li', 'asiatica', 'grisalho', '60+', '/img/pessoa_031.jpg'),
('Sasuke', 'asiatica', 'grisalho', '60+', '/img/pessoa_032.jpg'),
('Harumi', 'asiatica', 'preto', '26-40', '/img/pessoa_033.jpg'),
('Misaki', 'asiatica', 'castanho', '26-40', '/img/pessoa_034.jpg'),
('Jun', 'asiatica', 'preto', '13-17', '/img/pessoa_035.jpg'),
('Akemi', 'asiatica', 'preto', '0-5', '/img/pessoa_036.jpg'),
('Vanessa', 'parda', 'castanho', '5-12', '/img/pessoa_037.jpg'),
('Larissa', 'parda', 'preto', '5-12', '/img/pessoa_038.jpg'),
('Sergio', 'parda', 'castanho', '41-60', '/img/pessoa_039.jpg'),
('Isabela', 'parda', 'castanho', '41-60', '/img/pessoa_040.jpg'),
('Manuela', 'parda', 'castanho', '26-40', '/img/pessoa_041.jpg'),
('Erik', 'parda', 'castanho', '26-40', '/img/pessoa_042.jpg'),
('Gabriel', 'parda', 'castanho', '13-17', '/img/pessoa_043.jpg'),
('Lorena', 'parda', 'castanho', '13-17', '/img/pessoa_044.jpg'),
('Beatriz', 'parda', 'castanho', '60+', '/img/pessoa_045.jpg'),
('Miguel', 'parda', 'grisalho', '60+', '/img/pessoa_046.jpg'),
('Laura', 'parda', 'castanho', '0-5', '/img/pessoa_047.jpg'),
('Felipe', 'parda', 'preto', '18-25', '/img/pessoa_048.jpg'),
('Ruda', 'parda', 'preto', '41-60', '/img/pessoa_049.jpg'),
('Potira', 'indigena', 'grisalho', '41-60', '/img/pessoa_050.jpg'),
('Tupi', 'indigena', 'castanho', '0-5', '/img/pessoa_051.jpg'),
('Janaina', 'indigena', 'castanho', '0-5', '/img/pessoa_052.jpg'),
('Iara', 'parda', 'castanho', '18-25', '/img/pessoa_053.jpg'),
('Jade', 'parda', 'castanho', '18-25', '/img/pessoa_054.jpg'),
('Luna', 'parda', 'castanho', '13-17', '/img/pessoa_055.jpg'),
('Ester', 'parda', 'castanho', '13-17', '/img/pessoa_056.jpg'),
('Gustavo', 'parda', 'castanho', '5-12', '/img/pessoa_057.jpg'),
('Suzana', 'parda', 'castanho', '5-12', '/img/pessoa_058.jpg'),
('Ravi', 'parda', 'castanho', '26-40', '/img/pessoa_059.jpg'),
('Odair', 'parda', 'grisalho', '60+', '/img/pessoa_060.jpg');
