CREATE TABLE IF NOT EXISTS people_images (
    id SERIAL PRIMARY KEY,
    nome TEXT,
    etnia TEXT,
    cor_cabelo TEXT,
    idade INTEGER,
    label_etaria TEXT,
    caminho_imagem TEXT
);

TRUNCATE TABLE people_images RESTART IDENTITY CASCADE;

INSERT INTO people_images (nome, etnia, cor_cabelo, idade, label_etaria, caminho_imagem)
VALUES
('Julia',     'branca',   'grisalho', 64, 'Idoso',       '/img/pessoa_001.jpg'),
('Carlos',    'branca',   'grisalho', 70, 'Idoso',       '/img/pessoa_002.jpg'),
('Mariana',   'branca',   'castanho', 46, 'Meia-idade',  '/img/pessoa_003.jpg'),
('Sandra',    'branca',   'loiro',    52, 'Meia-idade',  '/img/pessoa_004.jpg'),
('Fernanda',  'branca',   'ruivo',    35, 'Adulto',      '/img/pessoa_005.jpg'),
('Lucas',     'branca',   'preto',    33, 'Adulto',      '/img/pessoa_006.jpg'),
('Marcela',   'branca',   'loiro',     7, 'Criança',     '/img/pessoa_007.jpg'),
('Marina',    'branca',   'preto',     4, 'Bebê',        '/img/pessoa_008.jpg'),
('Julio',     'branca',   'loiro',    10, 'Criança',     '/img/pessoa_009.jpg'),
('Helena',    'branca',   'loiro',     8, 'Criança',     '/img/pessoa_010.jpg'),
('Bruna',     'branca',   'castanho', 18, 'Jovem',       '/img/pessoa_011.jpg'),
('Rafaela',   'branca',   'loiro',    16, 'Adolescente', '/img/pessoa_012.jpg'),
('Luiz',      'negra',    'grisalho', 68, 'Idoso',       '/img/pessoa_013.jpg'),
('Marcelo',   'negra',    'preto',    50, 'Meia-idade',  '/img/pessoa_014.jpg'),
('Tais',      'negra',    'preto',    15, 'Adolescente', '/img/pessoa_015.jpg'),
('Michael',   'negra',    'preto',     9, 'Criança',     '/img/pessoa_016.jpg'),
('Djalma',    'negra',    'preto',    20, 'Jovem',       '/img/pessoa_017.jpg'),
('Michele',   'negra',    'castanho', 20, 'Jovem',       '/img/pessoa_018.jpg'),
('Francisco', 'negra',    'preto',    44, 'Meia-idade',  '/img/pessoa_019.jpg'),
('Thais',     'negra',    'preto',    50, 'Meia-idade',  '/img/pessoa_020.jpg'),
('Robson',    'negra',    'preto',    50, 'Meia-idade',  '/img/pessoa_021.jpg'),
('Marcos',    'negra',    'preto',    55, 'Meia-idade',  '/img/pessoa_022.jpg'),
('Samuel',    'negra',    'preto',    11, 'Criança',     '/img/pessoa_023.jpg'),
('Anderson',  'negra',    'preto',     1, 'Bebê',        '/img/pessoa_024.jpg'),
('Sakura',    'asiatica', 'preto',    10, 'Criança',     '/img/pessoa_025.jpg'),
('Haru',      'asiatica', 'preto',     6, 'Criança',     '/img/pessoa_026.jpg'),
('Ren',       'asiatica', 'preto',    30, 'Adulto',      '/img/pessoa_027.jpg'),
('Takeshi',   'asiatica', 'loiro',    20, 'Jovem',       '/img/pessoa_028.jpg'),
('Hiroshi',   'asiatica', 'preto',    43, 'Meia-idade',  '/img/pessoa_029.jpg'),
('Kakashi',   'asiatica', 'preto',    53, 'Meia-idade',  '/img/pessoa_030.jpg'),
('Li',        'asiatica', 'grisalho', 70, 'Idoso',       '/img/pessoa_031.jpg'),
('Sasuke',    'asiatica', 'grisalho', 73, 'Idoso',       '/img/pessoa_032.jpg'),
('Harumi',    'asiatica', 'preto',    28, 'Adulto',      '/img/pessoa_033.jpg'),
('Misaki',    'asiatica', 'castanho', 27, 'Adulto',      '/img/pessoa_034.jpg'),
('Yui',       'asiatica', 'preto',    15, 'Adolescente', '/img/pessoa_035.jpg'),
('Akemi',     'asiatica', 'preto',     1, 'Bebê',        '/img/pessoa_036.jpg'),
('Vanessa',   'parda',    'castanho', 11, 'Criança',     '/img/pessoa_037.jpg'),
('Larissa',   'parda',    'preto',     8, 'Criança',     '/img/pessoa_038.jpg'),
('Sergio',    'parda',    'castanho', 48, 'Meia-idade',  '/img/pessoa_039.jpg'),
('Isabela',   'parda',    'castanho', 57, 'Meia-idade',  '/img/pessoa_040.jpg'),
('Manuela',   'parda',    'castanho', 50, 'Meia-idade',  '/img/pessoa_041.jpg'),
('Erik',      'parda',    'preto',    34, 'Adulto',      '/img/pessoa_042.jpg'),
('Gabriel',   'parda',    'preto',    14, 'Adolescente', '/img/pessoa_043.jpg'),
('Lorena',    'parda',    'castanho', 12, 'Criança',     '/img/pessoa_044.jpg'),
('Beatriz',   'parda',    'grisalho', 70, 'Idoso',       '/img/pessoa_045.jpg'),
('Miguel',    'parda',    'grisalho', 68, 'Idoso',       '/img/pessoa_046.jpg'),
('Laura',     'parda',    'preto',     1, 'Bebê',        '/img/pessoa_047.jpg'),
('Felipe',    'parda',    'preto',    18, 'Jovem',       '/img/pessoa_048.jpg'),
('Ruda',      'parda',    'preto',    38, 'Adulto',      '/img/pessoa_049.jpg'),
('Cauã',      'indigena', 'grisalho', 60, 'Meia-idade',  '/img/pessoa_050.jpg'),
('Tupi',      'indigena', 'castanho',  1, 'Bebê',        '/img/pessoa_051.jpg'),
('Janaina',   'indigena', 'preto',     1, 'Bebê',        '/img/pessoa_052.jpg'),
('Iara',      'parda',    'preto',    22, 'Jovem',       '/img/pessoa_053.jpg'),
('Jade',      'parda',    'preto',    24, 'Jovem',       '/img/pessoa_054.jpg'),
('Luna',      'parda',    'castanho', 13, 'Adolescente', '/img/pessoa_055.jpg'),
('Ester',     'parda',    'castanho', 10, 'Criança',     '/img/pessoa_056.jpg'),
('Gustavo',   'parda',    'preto',     2, 'Bebê',        '/img/pessoa_057.jpg'),
('Suzana',    'parda',    'castanho',  9, 'Criança',     '/img/pessoa_058.jpg'),
('Ravi',      'parda',    'preto',    28, 'Adulto',      '/img/pessoa_059.jpg'),
('Odair',     'parda',    'grisalho', 58, 'Meia-idade',  '/img/pessoa_060.jpg');
