CREATE TABLE IF NOT EXISTS people_images (
    id SERIAL PRIMARY KEY,
    nome TEXT,
    etnia TEXT,
    cor_cabelo TEXT,
    idade INTEGER,
    label_etaria TEXT,
    caminho_imagem TEXT
);

TRUNCATE TABLE people_images RESTART IDENTITY CASCADE;

-- Coloquei uma idade em Int para pegar de maneira correta a idade e range de idade das pessoas
-- A primeira ideia era classificar pela label, porém é eficiente apenas para caso o usuário colocasse a label
INSERT INTO people_images (nome, etnia, cor_cabelo, idade, label_etaria, caminho_imagem)
VALUES
('Julia',     'branca',   'grisalho', 68, 'Idoso',       '/img/pessoa_001.jpg'),
('Carlos',    'branca',   'grisalho', 72, 'Idoso',       '/img/pessoa_002.jpg'),
('Mariana',   'branca',   'castanho', 45, 'Meia-idade',  '/img/pessoa_003.jpg'),
('Sandra',    'branca',   'loiro',    55, 'Meia-idade',  '/img/pessoa_004.jpg'),
('Fernanda',  'branca',   'ruivo',    32, 'Adulto',      '/img/pessoa_005.jpg'),
('Lucas',     'branca',   'preto',    28, 'Adulto',      '/img/pessoa_006.jpg'),
('Marcela',   'branca',   'loiro',     3, 'Bebê',        '/img/pessoa_007.jpg'),
('Marina',    'branca',   'preto',     4, 'Bebê',        '/img/pessoa_008.jpg'),
('Julio',     'branca',   'loiro',     9, 'Criança',     '/img/pessoa_009.jpg'),
('Lucas2',    'branca',   'loiro',    11, 'Criança',     '/img/pessoa_010.jpg'),
('Marina2',   'branca',   'castanho', 15, 'Adolescente', '/img/pessoa_011.jpg'),
('Rafaela',   'branca',   'loiro',    22, 'Jovem',       '/img/pessoa_012.jpg'),
('Luiz',      'negra',    'grisalho', 65, 'Idoso',       '/img/pessoa_013.jpg'),
('Marcelo',   'negra',    'preto',    78, 'Idoso',       '/img/pessoa_014.jpg'),
('Tais',      'negra',    'preto',    14, 'Adolescente', '/img/pessoa_015.jpg'),
('Michael',   'negra',    'preto',    16, 'Adolescente', '/img/pessoa_016.jpg'),
('Djalma',    'negra',    'preto',    20, 'Jovem',       '/img/pessoa_017.jpg'),
('Michele',   'negra',    'castanho', 23, 'Jovem',       '/img/pessoa_018.jpg'),
('Francisco', 'negra',    'preto',    35, 'Adulto',      '/img/pessoa_019.jpg'),
('Thais',     'negra',    'preto',    48, 'Meia-idade',  '/img/pessoa_020.jpg'),
('Robson',    'negra',    'preto',    52, 'Meia-idade',  '/img/pessoa_021.jpg'),
('Marcos',    'negra',    'preto',    58, 'Meia-idade',  '/img/pessoa_022.jpg'),
('Samuel',    'negra',    'preto',     8, 'Criança',     '/img/pessoa_023.jpg'),
('Anderson',  'negra',    'preto',     2, 'Bebê',        '/img/pessoa_024.jpg'),
('Kenji',     'asiatica', 'castanho', 10, 'Criança',     '/img/pessoa_025.jpg'),
('Yumi',      'asiatica', 'castanho',  7, 'Criança',     '/img/pessoa_026.jpg'),
('Hana',      'asiatica', 'castanho', 21, 'Jovem',       '/img/pessoa_027.jpg'),
('Takeshi',   'asiatica', 'loiro',    13, 'Adolescente', '/img/pessoa_028.jpg'),
('Mei',       'asiatica', 'preto',    43, 'Meia-idade',  '/img/pessoa_029.jpg'),
('Kakashi',   'asiatica', 'castanho', 57, 'Meia-idade',  '/img/pessoa_030.jpg'),
('Li',        'asiatica', 'grisalho', 63, 'Idoso',       '/img/pessoa_031.jpg'),
('Sasuke',    'asiatica', 'grisalho', 75, 'Idoso',       '/img/pessoa_032.jpg'),
('Harumi',    'asiatica', 'preto',    30, 'Adulto',      '/img/pessoa_033.jpg'),
('Misaki',    'asiatica', 'castanho', 38, 'Adulto',      '/img/pessoa_034.jpg'),
('Jun',       'asiatica', 'preto',    17, 'Adolescente', '/img/pessoa_035.jpg'),
('Akemi',     'asiatica', 'preto',     1, 'Bebê',        '/img/pessoa_036.jpg'),
('Vanessa',   'parda',    'castanho',  6, 'Criança',     '/img/pessoa_037.jpg'),
('Larissa',   'parda',    'preto',    11, 'Criança',     '/img/pessoa_038.jpg'),
('Sergio',    'parda',    'castanho', 41, 'Meia-idade',  '/img/pessoa_039.jpg'),
('Isabela',   'parda',    'castanho', 59, 'Meia-idade',  '/img/pessoa_040.jpg'),
('Manuela',   'parda',    'castanho', 27, 'Adulto',      '/img/pessoa_041.jpg'),
('Erik',      'parda',    'castanho', 36, 'Adulto',      '/img/pessoa_042.jpg'),
('Gabriel',   'parda',    'castanho', 15, 'Adolescente', '/img/pessoa_043.jpg'),
('Lorena',    'parda',    'castanho', 14, 'Adolescente', '/img/pessoa_044.jpg'),
('Beatriz',   'parda',    'castanho', 70, 'Idoso',       '/img/pessoa_045.jpg'),
('Miguel',    'parda',    'grisalho', 66, 'Idoso',       '/img/pessoa_046.jpg'),
('Laura',     'parda',    'castanho',  5, 'Bebê',        '/img/pessoa_047.jpg'),
('Felipe',    'parda',    'preto',    24, 'Jovem',       '/img/pessoa_048.jpg'),
('Ruda',      'parda',    'preto',    50, 'Meia-idade',  '/img/pessoa_049.jpg'),
('Potira',    'indigena', 'grisalho', 46, 'Meia-idade',  '/img/pessoa_050.jpg'),
('Tupi',      'indigena', 'castanho',  3, 'Bebê',        '/img/pessoa_051.jpg'),
('Janaina',   'indigena', 'castanho',  4, 'Bebê',        '/img/pessoa_052.jpg'),
('Iara',      'parda',    'castanho', 19, 'Jovem',       '/img/pessoa_053.jpg'),
('Jade',      'parda',    'castanho', 18, 'Jovem',       '/img/pessoa_054.jpg'),
('Luna',      'parda',    'castanho', 16, 'Adolescente', '/img/pessoa_055.jpg'),
('Ester',     'parda',    'castanho', 13, 'Adolescente', '/img/pessoa_056.jpg'),
('Gustavo',   'parda',    'castanho',  8, 'Criança',     '/img/pessoa_057.jpg'),
('Suzana',    'parda',    'castanho',  7, 'Criança',     '/img/pessoa_058.jpg'),
('Ravi',      'parda',    'castanho', 33, 'Adulto',      '/img/pessoa_059.jpg'),
('Odair',     'parda',    'grisalho', 75, 'Idoso',       '/img/pessoa_060.jpg');
